// Run with: bun test scripts/bump-version.test.mjs
import { afterEach, beforeEach, describe, expect, it } from 'bun:test'
import { mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { TAG_PREFIX, bumpVersion } from './bump-version.mjs'

let root

const CARGO_LOCK = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "base"
version = "0.1.0"
dependencies = [
 "suite-tauri",
]

[[package]]
name = "zachart-mentale"
version = "1.6.0"
dependencies = [
 "suite-tauri",
]

[[package]]
name = "zachart-mentale-extra"
version = "9.9.9"

[[package]]
name = "suite-tauri"
version = "0.1.0"
`

function writeApp(app, { version, cargoVersion = version, crate = app }) {
  const dir = join(root, 'apps', app)
  mkdirSync(join(dir, 'src-tauri'), { recursive: true })
  writeFileSync(join(dir, 'package.json'), `${JSON.stringify({ name: app, private: true, version, type: 'module' }, null, 2)}\n`)
  writeFileSync(
    join(dir, 'src-tauri', 'tauri.conf.json'),
    `${JSON.stringify({ productName: app, version, identifier: `com.clape.${app}` }, null, 2)}\n`,
  )
  writeFileSync(
    join(dir, 'src-tauri', 'Cargo.toml'),
    `[package]\nname = "${crate}"\nversion = "${cargoVersion}"\nedition = "2021"\n\n[dependencies]\ntauri = "2"\n`,
  )
}

const read = (...parts) => readFileSync(join(root, ...parts), 'utf8')
const versionsOf = app => ({
  package: JSON.parse(read('apps', app, 'package.json')).version,
  tauri: JSON.parse(read('apps', app, 'src-tauri', 'tauri.conf.json')).version,
  cargo: read('apps', app, 'src-tauri', 'Cargo.toml').match(/^version = "(.*)"$/m)[1],
  lock: read('Cargo.lock').match(new RegExp(`name = "${app}"\\r?\\nversion = "(.*)"`))[1],
})
const snapshot = () =>
  Object.fromEntries(
    ['apps/base/package.json', 'apps/base/src-tauri/tauri.conf.json', 'apps/base/src-tauri/Cargo.toml',
      'apps/zachart-mentale/package.json', 'apps/zachart-mentale/src-tauri/tauri.conf.json',
      'apps/zachart-mentale/src-tauri/Cargo.toml', 'Cargo.lock'].map(file => [file, read(...file.split('/'))]),
  )

beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), 'bump-'))
  // Zachar't's crate really did drift: the app and the installer said 1.20.5, Cargo said 1.6.0.
  writeApp('zachart-mentale', { version: '1.20.5', cargoVersion: '1.6.0' })
  writeApp('base', { version: '0.1.0' })
  writeFileSync(join(root, 'Cargo.lock'), CARGO_LOCK)
})

afterEach(() => rmSync(root, { recursive: true, force: true }))

describe('bumpVersion — calcul de la version', () => {
  it.each([
    ['patch', '1.20.6'],
    ['minor', '1.21.0'],
    ['major', '2.0.0'],
    ['3.4.5', '3.4.5'],
  ])('%s => %s', (arg, expected) => {
    expect(bumpVersion({ root, app: 'zachart-mentale', arg }).next).toBe(expected)
  })

  it('part de la version de tauri.conf.json, celle dont dérive le tag, pas de celle de Cargo', () => {
    expect(bumpVersion({ root, app: 'zachart-mentale', arg: 'patch' }).current).toBe('1.20.5')
  })
})

describe('bumpVersion — ce qui est écrit', () => {
  it('met la MÊME version dans package.json, tauri.conf.json, Cargo.toml et Cargo.lock (ce qui referme la dérive 1.20.5 / 1.6.0)', () => {
    bumpVersion({ root, app: 'zachart-mentale', arg: 'patch' })
    expect(versionsOf('zachart-mentale')).toEqual({ package: '1.20.6', tauri: '1.20.6', cargo: '1.20.6', lock: '1.20.6' })
  })

  it('ne touche qu\'à l\'app demandée', () => {
    const before = snapshot()
    bumpVersion({ root, app: 'base', arg: 'minor' })
    const after = snapshot()
    expect(versionsOf('base')).toEqual({ package: '0.2.0', tauri: '0.2.0', cargo: '0.2.0', lock: '0.2.0' })
    for (const file of Object.keys(before)) {
      if (file.startsWith('apps/zachart-mentale')) expect(after[file]).toBe(before[file])
    }
    expect(after['Cargo.lock']).toContain('name = "zachart-mentale"\nversion = "1.6.0"')
  })

  it('ne confond pas une crate avec une autre dont le nom commence pareil (Cargo.lock)', () => {
    bumpVersion({ root, app: 'zachart-mentale', arg: 'patch' })
    expect(read('Cargo.lock')).toContain('name = "zachart-mentale-extra"\nversion = "9.9.9"')
    expect(read('Cargo.lock')).toContain('name = "suite-tauri"\nversion = "0.1.0"')
  })

  it('ne modifie que la version de [package], pas celle d\'une dépendance', () => {
    const cargo = join(root, 'apps', 'base', 'src-tauri', 'Cargo.toml')
    writeFileSync(cargo, `${readFileSync(cargo, 'utf8')}serde = { version = "1.0.1" }\n`)
    bumpVersion({ root, app: 'base', arg: 'patch' })
    expect(read('apps', 'base', 'src-tauri', 'Cargo.toml')).toContain('serde = { version = "1.0.1" }')
    expect(versionsOf('base').cargo).toBe('0.1.1')
  })

  it('refuse une crate dont [package] n\'a pas de version, même si une dépendance en a une (elle ne doit pas être « bumpée » à sa place)', () => {
    const cargo = join(root, 'apps', 'base', 'src-tauri', 'Cargo.toml')
    writeFileSync(cargo, '[package]\nname = "base"\nedition = "2021"\n\n[dependencies]\nserde = { version = "1.0.1" }\nother = "1"\n\n[dependencies.tauri]\nversion = "2"\n')
    const before = snapshot()
    expect(() => bumpVersion({ root, app: 'base', arg: 'patch' })).toThrow(/Cargo\.toml/)
    expect(snapshot()).toEqual(before)
  })

  it('garde le format des fichiers JSON (2 espaces, retour à la ligne final)', () => {
    bumpVersion({ root, app: 'base', arg: 'patch' })
    const text = read('apps', 'base', 'package.json')
    expect(text.endsWith('}\n')).toBe(true)
    expect(text).toContain('\n  "version": "0.1.1"')
  })

  it('garde les fins de ligne CRLF de Cargo.toml et de Cargo.lock', () => {
    const cargo = join(root, 'apps', 'base', 'src-tauri', 'Cargo.toml')
    writeFileSync(cargo, readFileSync(cargo, 'utf8').replace(/\n/g, '\r\n'))
    writeFileSync(join(root, 'Cargo.lock'), CARGO_LOCK.replace(/\n/g, '\r\n'))
    bumpVersion({ root, app: 'base', arg: 'patch' })
    expect(read('apps', 'base', 'src-tauri', 'Cargo.toml')).toContain('version = "0.1.1"\r\n')
    expect(read('Cargo.lock')).toContain('name = "base"\r\nversion = "0.1.1"\r\n')
    expect(read('Cargo.lock')).not.toMatch(/[^\r]\n/)
  })
})

describe('bumpVersion — tag et commandes', () => {
  it('zachart-mentale a un préfixe court, les autres apps prennent leur nom', () => {
    expect(TAG_PREFIX['zachart-mentale']).toBe('zachart')
    expect(bumpVersion({ root, app: 'zachart-mentale', arg: 'patch' }).tag).toBe('zachart-v1.20.6')
    expect(bumpVersion({ root, app: 'base', arg: 'patch' }).tag).toBe('base-v0.1.1')
  })

  it('imprime des commandes git qui n\'ajoutent que les fichiers de l\'app et le Cargo.lock', () => {
    const { commands } = bumpVersion({ root, app: 'base', arg: 'patch' })
    const text = commands.join('\n')
    expect(text).toContain('git add apps/base/package.json apps/base/src-tauri/tauri.conf.json apps/base/src-tauri/Cargo.toml Cargo.lock')
    expect(text).toContain('git tag base-v0.1.1')
    expect(text).toContain('git push origin base-v0.1.1')
    expect(text).not.toContain('git add -A')
    expect(text).not.toContain('git add .')
  })
})

describe('bumpVersion — refus, et rien n\'est écrit', () => {
  it.each(['', 'bogus', '1.2', '1.2.3.4', 'v1.2.3', '1.2.x', '-1.0.0', ' patch'])('refuse l\'argument %j', arg => {
    const before = snapshot()
    expect(() => bumpVersion({ root, app: 'base', arg })).toThrow(/version|patch/i)
    expect(snapshot()).toEqual(before)
  })

  it.each(['nope', '', '../etc', 'apps/base', 'base/../base'])('refuse l\'app %j', app => {
    const before = snapshot()
    expect(() => bumpVersion({ root, app, arg: 'patch' })).toThrow(/app/i)
    expect(snapshot()).toEqual(before)
  })

  it('refuse quand la crate n\'est pas dans Cargo.lock, sans rien écrire (pas de moitié de bump)', () => {
    writeFileSync(join(root, 'Cargo.lock'), CARGO_LOCK.replace('name = "base"', 'name = "autre"'))
    const before = snapshot()
    expect(() => bumpVersion({ root, app: 'base', arg: 'patch' })).toThrow(/Cargo\.lock/)
    expect(snapshot()).toEqual(before)
  })

  it('refuse quand la version de tauri.conf.json est illisible', () => {
    const conf = join(root, 'apps', 'base', 'src-tauri', 'tauri.conf.json')
    writeFileSync(conf, JSON.stringify({ productName: 'base' }))
    const before = snapshot()
    expect(() => bumpVersion({ root, app: 'base', arg: 'patch' })).toThrow(/tauri\.conf\.json/)
    expect(snapshot()).toEqual(before)
  })

  it('ne laisse pas de fichier temporaire', () => {
    bumpVersion({ root, app: 'base', arg: 'patch' })
    expect(readdirSync(root).sort()).toEqual(['Cargo.lock', 'apps'])
  })
})
